version: 0.2

phases:
  install:
    runtime-versions:
      commands:
      curl -SLO https://deb.nodesource.com/nsolid_setup_deb.sh
      chmod 500 nsolid_setup_deb.sh
      ./nsolid_setup_deb.sh 18
      apt-get install nodejs -y
  pre_build:
    commands:
      #install the react/NodeJS dependencies
      - npm install
  build:
    commands:
      #transform reactJS code to static html/js/css
      - npm run build 
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build