version: 0.2

phases:
  install:
    runtime-versions:
      commands:
      pkgin -y install nodejs
  pre_build:
    commands:
      #install the react/NodeJS dependencies
      - npm install
  build:
    commands:
      #transform reactJS code to static html/js/css
      - npm run build 
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build