version: 0.2

phases:
  install:
    runtime-versions:
      commands:
        #echo installing nodeJS & npm
        - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
        #install nodejs & npm
        - apt-get install -y nodejs
  pre_build:
    commands:
      #install the react/NodeJS dependencies
      - npm install
  build:
    commands:
      #transform reactJS code to static html/js/css
      - npm run build 
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build