version: 0.2

phases:
  install:
    runtime-versions:
      commands:
      #download nodeJS & npm
      - curl -fsSL https://deb.nodesource.com/setup_20.x | bash - 
      #install nodeJS & npm
      - apt-get install -y nodejs
  pre_build:
    commands:
      #install the react/NodeJS dependencies
      - npm install
  build:
    commands:
      #transform reactJS code to static html/js/css
      - npm run build 
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build