version: 0.2

phases:
  install:
    runtime-versions:
      commands:
        #echo installing nodeJS version 20...
        - curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
        - apt-get install -y nodejs
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build 
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build