version: 0.2

phases:
  install:
    runtime-versions:
      commands:
        sudo apt-get update
        sudo apt-get install -y ca-certificates curl gnupg
        sudo mkdir -p /etc/apt/keyrings
        curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
  pre_build:
    commands:
      #install the react/NodeJS dependencies
      - npm install
  build:
    commands:
      #transform reactJS code to static html/js/css
      - npm run build 
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build